### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by 1ccs-todd** [RiffSphere/Collectarr#5]
Environment:
TrueNAS jail - FreeBSD v12.2-p15
Python v3.8
Radarr v4.1.0.6175

Testing with dryrun=True

Results are:
[22-06-29 03:59:42] INFO - Config Loaded
[22-06-29 03:59:42] INFO - API tested succesfully
[22-06-29 03:59:42] INFO - Rootfolder parsed
[22-06-29 03:59:42] INFO - *****************************
[22-06-29 03:59:42] INFO - * Load collection blacklist *
[22-06-29 03:59:42] INFO - *****************************
[22-06-29 03:59:42] INFO - *****************************************************
[22-06-29 03:59:42] INFO - * Removing collectarr lists disabled in config file *
[22-06-29 03:59:42] INFO - *****************************************************
[22-06-29 03:59:42] INFO - ****************************************************************
[22-06-29 03:59:42] INFO - * Removing collectarr collection lists disabled in config file *
[22-06-29 03:59:42] INFO - ****************************************************************
[22-06-29 03:59:42] INFO - ****************************
[22-06-29 03:59:42] INFO - * Start adding collections *
[22-06-29 03:59:42] INFO - ****************************
[22-06-29 04:00:21] INFO - Checking 2258 movies in collection
Traceback (most recent call last):
  File "./collectarr.py", line 564, in <module>
    AddCollections()
  File "./collectarr.py", line 266, in AddCollections
    colls.update({str(movie["collection"]["tmdbId"]): movie["collection"]["name"]})
KeyError: 'name'

**Comment by 1ccs-todd** [comment]
clean install on bsd 13.1 with python 3.9 works again.

**Comment by wuast94** [comment]
got the same with docker and running locally, so this issue can be reopened
