### ISSUE TITLE
KeyError: 'name' on startup

### ISSUE THREAD

**Issue by RupertDeRuyver** [RiffSphere/Collectarr#6]
Here are the logs:
```
[24-04-17 09:53:55] INFO - Config Loaded
[24-04-17 09:53:55] INFO - API tested succesfully
[24-04-17 09:53:55] INFO - Rootfolder parsed
[24-04-17 09:53:55] INFO - *****************************
[24-04-17 09:53:55] INFO - * Load collection blacklist *
[24-04-17 09:53:55] INFO - *****************************
[24-04-17 09:53:55] INFO - *****************************************************
[24-04-17 09:53:55] INFO - * Removing collectarr lists disabled in config file *
[24-04-17 09:53:55] INFO - *****************************************************
[24-04-17 09:53:55] INFO - ****************************************************************
[24-04-17 09:53:55] INFO - * Removing collectarr collection lists disabled in config file *
[24-04-17 09:53:55] INFO - ****************************************************************
[24-04-17 09:53:55] INFO - ****************************
[24-04-17 09:53:55] INFO - * Start adding collections *
[24-04-17 09:53:55] INFO - ****************************
[24-04-17 09:53:55] INFO - Checking 173 movies in collection
Traceback (most recent call last):
  File "/app/collectarr.py", line 564, in <module>
    AddCollections()
  File "/app/collectarr.py", line 266, in AddCollections
    colls.update({str(movie["collection"]["tmdbId"]): movie["collection"]["name"]})
KeyError: 'name'
```

This is the config file:
```
[tmdb]
; tmdb apiKey
;       Moved to top for easy editing
;       Can be kept empty
apiKey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

[Radarr]
; Radarr settings
;   Host
;        Don't include http(s) or /
host=192.168.0.151

;   Port
;       Just the port number, no :
port=7878
;   URLbase
;       If you set URL base in Radarr, enter it here
;       Should be in the form "/radarr"
URLbase=
;   apiKey
;       Your api key
apiKey=f0b196fc54494de28112d30fb154960b
;   https
;        True to use https, False to use http
https=False

[Collectarr]
; Program settings
;   dryrun
;       If set to True, program will run as configured, but not make changes to Radarr
;       Can be used to test settings and check log
dryrun=false
;   removealllists
;       As expected, removing all current lists from Radarr
;       WARNING: can not be un-done and should be False
;       Line can even be removed from config
removealllists=False
;   removeblacklistedlist
;       Remove lists containing a blacklisted id
;       Either manually or automatically added
removeblacklistedlists=False
;   removeCollectarractorlists
;       Remove all actor lists previously added by Collectarr
;       This only removes the lists, not the movies
removeCollectarractorlists=False
;   removeCollectarrcollectionlists
;       Remove all actor lists previously added by Collectarr
;       This only removes the lists, not the movies
removeCollectarrcollectionlists=False
;   addcollections
;       Execute the add collections for all (monitored if set) movies function
;       Suggest to keep True, since this is the main function of the program
addcollections=True
;   addactors
;       Enable adding actors
addactors=False
;   Rootfolder
;       first: Querry Radarr for all configured rootfolders, and use the first configured
;       movie: Set rootfolder to movie path without the movie name
rootfolder=first
;   movielistnameaddon
;       Lists added will be named according to the collection name provided by Radarr
;       Add a personal suffix to recognize list is added by Collectarr
;       Will also be used to remove lists added by Collectarr
movielistnameaddon= - Collection Added by Collectarr
;   movielistnameaddon
;       Lists added will be named according to the collection name provided by Radarr
;       Add a personal suffix to recognize list is added by Collectarr
;       Will also be used to remove lists added by Collectarr
actorlistnameaddon= - Actor Added by Collectarr

[Log]
; Log settings
;   quiet
;       Don't log to command line.
;       Set False for docker or debugging.
quiet=False
;   nolog
;       Log nothing if you don't care anyway
nolog=False
;   nocollectionlog
;       Log movies in Radarr that are not part of a collection
;       Suggest False to limit log file
nocollectionlog=False
;   loginfo
;       Shows more information about actions taken
;       Suggest True, else only error and list adding is logged.
loginfo=True

[Movie]
; Movie information used for lists creation
;   Only create lists for movies that are monitored
;       If you have multiple movies of 1 collection, it will create a list if 1 of them is monitored
monitoredonly=False
;   enabled
;       Enable the movie list in Radarr
;       Suggest True, else the list will not be used until (manually) enabled
enabled=True
;   enableAuto
;       Add movies from the list to Radarr
;       Strongly suggest to keep True, or Radarr wont add movies from the list
;       Set shouldMonitor to False if you don't want Radarr to monitor the movies added
enableAuto=True
;   shouldMonitor
;       Have Radarr monitor movies added by list
shouldMonitor=True
;   searchOnAdd
;       Have Radarr search movies when added
searchOnAdd=True

[Actor]
; Actor information used for list creation
;   monitoredonly
;       only count actor appearing if movie is monitored
monitoredonly=false
;   enabled
;       Enable the actor list in Radarr
;       Suggest True, else the list will not be used until (manually) enabled
enabled=True
;   enableAuto
;       Add movies from the list to Radarr
;       Strongly suggest to keep True, or Radarr wont add movies from the list
;       Set shouldMonitor to False if you don't want Radarr to monitor the movies added
enableAuto=True
;   shouldMonitor
;       Have Radarr monitor movies added by list
shouldMonitor=True
;   searchOnAdd
;       Have Radarr search movies when added
searchOnAdd=True
;   countvoice
;       Some voice actors appear in many animated movies, doing a voice, often for small rolls
;       This allows to not count an actor doing voice in a movie
countvoice=False
;   countuncredited
;       Sometimes actors are not credited in the movie, but TMDB still lists them
;       This allows to not count uncredited actors when making lists
countuncredited=False
;   actormin
;       How often should an actor be in the (monitored if set) movies before a list is added
actormin=20
```

**Comment by bhunt01** [comment]
Any solution to this issue? Having the same problem. 

Tried changing "nocollectionlog=False" to True and it shows that it did process 12 movies without collections before throwing that error.

**Comment by pellenbe** [comment]
Also experiencing the same issue.

**Comment by kikearciniegas** [comment]
me three! is this abandoned?

**Comment by kikearciniegas** [comment]
From copilot...

> This means that for at least one movie in your data, movie["collection"] does not have a "name" key. This can happen if:
> 
> The movie is not part of a collection (so movie["collection"] is None or missing keys).
> The API response is missing the "name" field for some collections.
> To fix this, you should add a check before accessing "name" and "tmdbId" to ensure both keys exist in movie["collection"]. If either is missing, skip that movie or handle it gracefully.
